version: '3.4'

services:
  postgres3 :
    container_name: postgres3
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
      #- ./data:/data/db
    environment:
       - POSTGRES_HOST_AUTH_METHOD=trust
       - POSTGRES_USER=postgres
       - POSTGRES_DB=testDb
    ports:
      - "5432:5432"
  
  mongo3:
    container_name: mongo3
    restart: always
    volumes:
     - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
     - "27017:27017"
   
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
     - 5672:5672
     - 15672:15672
     

  contact.api:
    container_name: contactservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MyWebApiConection=User ID=postgres;Server=postgres3;Port=5432;Database=testDb;Integrated Security=true;Pooling=true;
      - "RabbitMq:HostName=rabbitmq"
    depends_on: 
        - postgres3
        - rabbitmq
    ports:
      - "8000:80"
    volumes:
      - ${HOME}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https:ro

  report.api:
   container_name: reportservice
   environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - "MongoDbSettings:MongoDB=mongodb://mongo3:27017"
    - "RabbitMq:HostName=rabbitmq"
   depends_on: 
     - mongo3
     - rabbitmq
   volumes:
     - ${HOME}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
     - ${HOME}/ASP.NET/Https:/root/.aspnet/https:ro
   ports:
    - "8001:80"

  apigateway:
    container_name: apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
    - contact.api
    - report.api
    ports:
      - "5000:80"
    volumes:
      - ${HOME}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https:ro
